Updated version to 2.3.1
Crana-Inc/graphql-engine-heroku pull request #1
Opened 2022-03-28 14:15 UTC by HassanNiazi

2022-03-30 10:52 UTC, HassanNiazi commented
Don't merge this; Infact fetch from upstream, and close this one once story is merged.

2022-04-11 14:00 UTC, vladdy-dotcom approved these changes

2022-04-20 14:42 UTC, vladdy-dotcom requested changes

2022-04-20 14:42 UTC, vladdy-dotcom commented on Dockerfile
> +FROM hasura/graphql-engine:v2.4.0
2.5 is out

2022-04-20 14:46 UTC, vladdy-dotcom approved these changes

2022-04-26 12:08 UTC, merged